name: Parallel Cypress Tests

on: 
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # the actual items in the array do not matter,
        # just the number - to force CI to sping 3 copies
        # of the current job in parallel
        machines: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Install a project with a clean slate
        run: |
          npm install
          $(npm bin)/cypress verify

      - name: Run Cypress tests
        run: npm run cypress-remote-sanity-pack
        continue-on-error: true

      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
      
